//
// Created by Daniel Agu on 10/20/2020.
//

#ifndef PROJECT_1_DOUBLY_LINKED_LIST_CS2337DANIELAGU_LINKEDLISTEXCEPTION_H
#define PROJECT_1_DOUBLY_LINKED_LIST_CS2337DANIELAGU_LINKEDLISTEXCEPTION_H

class LinkedListException {

};

#include <iostream>
using namespace std;

#endif //PROJECT_1_DOUBLY_LINKED_LIST_CS2337DANIELAGU_LINKEDLISTEXCEPTION_H